# Generated by Django 5.0.2 on 2024-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='url عنوان در')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('is_activate', models.BooleanField()),
            ],
        ),
    ]
