# Generated by Django 5.0.2 on 2024-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_producttag_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/static/blogs/images', verbose_name='عکس محصول'),
        ),
    ]
