# Generated by Django 5.0.2 on 2024-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('family_name', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('message', models.TextField(max_length=350, verbose_name='متن پیام')),
                ('created_data', models.DateField(verbose_name='تاریخ ایجاد')),
                ('is_read_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'راه های تماس با ما',
            },
        ),
    ]
